### ISSUE TITLE
Make The History Page Configurable

### ISSUE THREAD

**Issue by JosiahDumitrescuTPM** [TPM-Repos/ModifiedCorporateTheme#21]
Modify the config.js file to let the user chose if running spec show up or not. The history.js file contains the code to control this.

**Comment by jccaswell** [comment]
![image](https://github.com/user-attachments/assets/6ed21263-75a4-48c1-b69e-3b6657fc8bb0)

![image](https://github.com/user-attachments/assets/b96e7af0-1214-4a1f-9e0f-59cf81b746bc)
